from typing import TypedDict, Optional, Dict, Any, List, Literal
from langchain_core.messages import BaseMessage

class SpecialistFindings(TypedDict, total=False):
    """Findings generated by specialist agents in the committee."""
    quant: Optional[Dict[str, Any]]
    solvency: Optional[Dict[str, Any]]
    forensic: Optional[Dict[str, Any]]

class RiskReview(TypedDict, total=False):
    """Audit verdict rendered by the Adversarial Risk & Compliance Officer."""
    status: Literal["APPROVED", "VETOED_RETRY", "VETOED_REJECTED"]
    violations: List[str]
    risk_score: float                # 0.0 (Safe) to 10.0 (Extreme Hazard)
    mandate_directive: Optional[str] # Instructions for the Quant to re-hedge the strategy
    summary: str

class AgentState(TypedDict):
    """
    Core state for AlphaAgent Hierarchical Multi-Agent Graph.
    Tracks user intent, specialist committee findings, code execution,
    adversarial risk audits, self-healing retries, and executive memoranda.
    """
    query: str
    intent: str                   # "backtest", "financial_health", "filing_qa", "committee", or "unknown"
    ticker: str                   # e.g. "AAPL", "BA", "NVDA"
    
    # Committee specialist findings
    specialist_findings: Optional[SpecialistFindings]
    
    # Quant Researcher & Code Execution state
    code: str                     # Generated backtest Python code
    execution_output: Optional[Dict[str, Any]] # Metrics returned by local execution
    error_log: Optional[str]      # Captured stderr/traceback if code fails
    retry_count: int              # Number of code self-healing attempts
    max_retries: int              # Maximum allowed code retries (default: 3)
    metrics: Optional[Dict[str, Any]] # Formatted financial or performance metrics
    chart_path: Optional[str]     # Path to generated equity curve / chart
    
    # SEC 10-K Qualitative RAG state
    sources: Optional[List[Dict[str, Any]]] # Retrieved RAG document citations & metadata
    
    # Adversarial Risk & Compliance Officer state
    risk_review: Optional[RiskReview]       # Risk Officer's audit verdict & directives
    risk_review_count: int                  # Re-hedging cycle counter
    max_risk_reviews: int                   # Maximum allowed re-hedge attempts (default: 2)
    
    # Synthesis & Message History
    final_report: str             # Final LLM synthesis report / Investment Memorandum
    messages: List[BaseMessage]   # Message history for agent tracking
